framework:
    notifier:
        chatter_transports:
            discord: '%env(DISCORD_DSN)%'
        #    slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        #texter_transports:
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['discord']
            high: ['discord']
            medium: ['discord']
            low: ['discord']
        admin_recipients:
            - { email: admin@example.com }
